name: Test on Linux and macOS

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node: [18, 20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Install required node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Test package installation
        run: sudo npm install
