name: Test on Windows

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  Test:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          show-progress: false

      - name: Install required node.js version
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Test package installation
        run: npm install
